# Task 1

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./Corona_NLP_Train.csv')

In [4]:
df

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment
0,3799,48751,London,16-03-2020,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...,Neutral
1,3800,48752,UK,16-03-2020,advice Talk to your neighbours family to excha...,Positive
2,3801,48753,Vagabonds,16-03-2020,Coronavirus Australia: Woolworths to give elde...,Positive
3,3802,48754,NaN,16-03-2020,My food stock is not the only one which is emp...,Positive
4,3803,48755,NaN,16-03-2020,"Me, ready to go at supermarket during the #COV...",Extremely Negative
...,...,...,...,...,...,...
41152,44951,89903,"Wellington City, New Zealand",14-04-2020,Airline pilots offering to stock supermarket s...,Neutral
41153,44952,89904,NaN,14-04-2020,Response to complaint not provided citing COVI...,Extremely Negative
41154,44953,89905,NaN,14-04-2020,You know itÂs getting tough when @KameronWild...,Positive
41155,44954,89906,NaN,14-04-2020,Is it wrong that the smell of hand sanitizer i...,Neutral
41156,44955,89907,i love you so much || he/him,14-04-2020,@TartiiCat Well new/used Rift S are going for ...,Negative

In [5]:
df.shape

(41157, 6)

In [6]:
df.columns

Index(['UserName', 'ScreenName', 'Location', 'TweetAt', 'OriginalTweet',
       'Sentiment'],
      dtype='str')

In [7]:
df['Sentiment'].nunique()

5

In [8]:
df['Sentiment'].value_counts()

Sentiment
Positive              11422
Negative               9917
Neutral                7713
Extremely Positive     6624
Extremely Negative     5481
Name: count, dtype: int64

In [9]:
df.head(10)

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment
0,3799,48751,London,16-03-2020,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...,Neutral
1,3800,48752,UK,16-03-2020,advice Talk to your neighbours family to excha...,Positive
2,3801,48753,Vagabonds,16-03-2020,Coronavirus Australia: Woolworths to give elde...,Positive
3,3802,48754,NaN,16-03-2020,My food stock is not the only one which is emp...,Positive
4,3803,48755,NaN,16-03-2020,"Me, ready to go at supermarket during the #COV...",Extremely Negative
5,3804,48756,"ÃT: 36.319708,-82.363649",16-03-2020,As news of the regionÂs first confirmed COVID...,Positive
6,3805,48757,"35.926541,-78.753267",16-03-2020,Cashier at grocery store was sharing his insig...,Positive
7,3806,48758,Austria,16-03-2020,Was at the supermarket today. Didn't buy toile...,Neutral
8,3807,48759,"Atlanta, GA USA",16-03-2020,Due to COVID-19 our retail store and classroom...,Positive
9,3808,48760,"BHAVNAGAR,GUJRAT",16-03-2020,"For corona prevention,we should stop to buy th...",Negative

# Task 2

In [10]:
df = df.drop(columns=["UserName", "ScreenName", "Location", "TweetAt"])

In [11]:
df

                                           OriginalTweet           Sentiment
0      @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...             Neutral
1      advice Talk to your neighbours family to excha...            Positive
2      Coronavirus Australia: Woolworths to give elde...            Positive
3      My food stock is not the only one which is emp...            Positive
4      Me, ready to go at supermarket during the #COV...  Extremely Negative
...                                                  ...                 ...
41152  Airline pilots offering to stock supermarket s...             Neutral
41153  Response to complaint not provided citing COVI...  Extremely Negative
41154  You know itÂs getting tough when @KameronWild...            Positive
41155  Is it wrong that the smell of hand sanitizer i...             Neutral
41156  @TartiiCat Well new/used Rift S are going for ...            Negative

[41157 rows x 2 columns]

In [12]:
sentiment_map = {
  "Extremely Positive": 0,
  "Extremely Negative": 1,
  "Positive": 2,
  "Neutral": 3,
  "Negative": 4
}

df["Sentiment"] = df["Sentiment"].map(sentiment_map)

In [13]:
df

                                           OriginalTweet  Sentiment
0      @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...          3
1      advice Talk to your neighbours family to excha...          2
2      Coronavirus Australia: Woolworths to give elde...          2
3      My food stock is not the only one which is emp...          2
4      Me, ready to go at supermarket during the #COV...          1
...                                                  ...        ...
41152  Airline pilots offering to stock supermarket s...          3
41153  Response to complaint not provided citing COVI...          1
41154  You know itÂs getting tough when @KameronWild...          2
41155  Is it wrong that the smell of hand sanitizer i...          3
41156  @TartiiCat Well new/used Rift S are going for ...          4

[41157 rows x 2 columns]

In [14]:
df["OriginalTweet"] = df["OriginalTweet"].str.lower()

In [15]:
df

                                           OriginalTweet  Sentiment
0      @menyrbie @phil_gahan @chrisitv https://t.co/i...          3
1      advice talk to your neighbours family to excha...          2
2      coronavirus australia: woolworths to give elde...          2
3      my food stock is not the only one which is emp...          2
4      me, ready to go at supermarket during the #cov...          1
...                                                  ...        ...
41152  airline pilots offering to stock supermarket s...          3
41153  response to complaint not provided citing covi...          1
41154  you know itâs getting tough when @kameronwild...          2
41155  is it wrong that the smell of hand sanitizer i...          3
41156  @tartiicat well new/used rift s are going for ...          4

[41157 rows x 2 columns]

In [16]:
from nltk.corpus import stopwords
stop_words = stopwords.words("english")

In [17]:
original_tweet = df["OriginalTweet"]
filtered_sentences = []
for i in original_tweet:
  filtered_word = []
  for j in i.split():
    if j not in stop_words:
      filtered_word.append(j)
  filtered_sentences.append(" ".join(filtered_word))
df['OriginalTweet'] = filtered_sentences
df

                                           OriginalTweet  Sentiment
0      @menyrbie @phil_gahan @chrisitv https://t.co/i...          3
1      advice talk neighbours family exchange phone n...          2
2      coronavirus australia: woolworths give elderly...          2
3      food stock one empty... please, panic, enough ...          2
4      me, ready go supermarket #covid19 outbreak. pa...          1
...                                                  ...        ...
41152  airline pilots offering stock supermarket shel...          3
41153  response complaint provided citing covid-19 re...          1
41154  know itâs getting tough @kameronwilds rationi...          2
41155  wrong smell hand sanitizer starting turn on? #...          3
41156  @tartiicat well new/used rift going $700.00 am...          4

[41157 rows x 2 columns]

In [18]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

original_tweet = df["OriginalTweet"]
stemmed_sentences = []
for i in original_tweet:
  stemmed_word = []
  for j in i.split():
    stemmed_word.append(stemmer.stem(j))
  stemmed_sentences.append(" ".join(stemmed_word))
df['OriginalTweet'] = stemmed_sentences

df

                                           OriginalTweet  Sentiment
0      @menyrbi @phil_gahan @chrisitv https://t.co/if...          3
1      advic talk neighbour famili exchang phone numb...          2
2      coronaviru australia: woolworth give elderly, ...          2
3      food stock one empty... please, panic, enough ...          2
4      me, readi go supermarket #covid19 outbreak. pa...          1
...                                                  ...        ...
41152  airlin pilot offer stock supermarket shelv #nz...          3
41153  respons complaint provid cite covid-19 relat d...          1
41154  know itâ get tough @kameronwild ration toilet...          2
41155  wrong smell hand sanit start turn on? #coronav...          3
41156  @tartiicat well new/us rift go $700.00 amazon ...          4

[41157 rows x 2 columns]

# Task 3

In [19]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1785693281.119036  212927 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1785693281.124519  212927 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1785693281.554934  212927 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1785693283.598737  212927 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1785693283.601222  212927 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [20]:
x = df["OriginalTweet"]
y = df["Sentiment"]

In [21]:
x_train, x_test, y_train, y_test = train_test_split(
  x,
  y,
  test_size=0.2,
  random_state=42,
  stratify=y
)

In [22]:
vec = TfidfVectorizer(max_features=12000, ngram_range=(1, 3))

In [23]:
x_train_vec = vec.fit_transform(x_train)
x_test_vec = vec.transform(x_test)

X_train = x_train_vec.toarray().astype("float32")
X_test = x_test_vec.toarray().astype("float32")

X_train.shape

(32925, 12000)

In [24]:
from tensorflow.keras.utils import to_categorical
y_train_onehot = to_categorical(y_train, num_classes = 5)
y_test_onehot = to_categorical(y_test, num_classes = 5)

# Task 4

In [25]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from tensorflow.keras import Sequential, Input
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

import matplotlib.pyplot as plt

In [26]:
modelA = Sequential([
    Input(shape= (X_train.shape[1],)),
    Dense(256, activation="leaky_relu"),
    Dropout(0.2),
    Dense(128, activation="relu"),
    Dropout(0.2),
    Dense(64, activation="relu"),
    Dense(5, activation="softmax")
])

E0000 00:00:1785693292.304963  212927 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [27]:
modelA.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

In [ ]:
historyA = modelA.fit(
    X_train,
    y_train_onehot,
    validation_split=0.15,
    epochs=50,
    batch_size=32,
    verbose=1
)

Epoch 1/50
875/875 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - accuracy: 0.5038 - loss: 1.1622 - val_accuracy: 0.5898 - val_loss: 0.9967
Epoch 2/50
875/875 ━━━━━━━━━━━━━━━━━━━━ 19s 22ms/step - accuracy: 0.7129 - loss: 0.7449 - val_accuracy: 0.6086 - val_loss: 0.9830
Epoch 3/50
875/875 ━━━━━━━━━━━━━━━━━━━━ 19s 22ms/step - accuracy: 0.8151 - loss: 0.4943 - val_accuracy: 0.5912 - val_loss: 1.1912
Epoch 4/50
875/875 ━━━━━━━━━━━━━━━━━━━━ 19s 22ms/step - accuracy: 0.8867 - loss: 0.3065 - val_accuracy: 0.5835 - val_loss: 1.4994
Epoch 5/50
875/875 ━━━━━━━━━━━━━━━━━━━━ 19s 22ms/step - accuracy: 0.9313 - loss: 0.1928 - val_accuracy: 0.5768 - val_loss: 1.8842
Epoch 6/50
875/875 ━━━━━━━━━━━━━━━━━━━━ 19s 22ms/step - accuracy: 0.9581 - loss: 0.1208 - val_accuracy: 0.5689 - val_loss: 2.2567
Epoch 7/50
875/875 ━━━━━━━━━━━━━━━━━━━━ 20s 22ms/step - accuracy: 0.9701 - loss: 0.0883 - val_accuracy: 0.5637 - val_loss: 2.5611
Epoch 8/50
875/875 ━━━━━━━━━━━━━━━━━━━━ 18s 21ms/step - accuracy: 0.9759 - loss: 0.0729 - val_accuracy: 0.5700 - val_loss: 2.8304
Epoch 9/50
875/875 ━━━━━━━━━━━━━━━━━━━━ 19s 21ms/step - accuracy: 0.9803 - loss: 0.0580 - val_accuracy: 0.5598 - val_loss: 2.9516
Epoch 10/50
875/875 ━━━━━━━━━━━━━━━━━━━━ 18s 21ms/step - accuracy: 0.9809 - loss: 0.0585 - val_accuracy: 0.5639 - val_loss: 2.8469
Epoch 11/50
647/875 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - accuracy: 0.9868 - loss: 0.0415

In [ ]:
def plot_history(history, title):

    plt.figure(figsize=(12,4))

    # Accuracy
    plt.subplot(1,2,1)
    plt.plot(history.history["accuracy"])
    plt.plot(history.history["val_accuracy"])
    plt.title(title + " Accuracy")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend(["Train","Validation"])


    # Loss
    plt.subplot(1,2,2)
    plt.plot(history.history["loss"])
    plt.plot(history.history["val_loss"])
    plt.title(title + " Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.legend(["Train","Validation"])

    plt.show()

In [ ]:
plot_history(historyA, "Model A")

In [ ]:
pred_A = modelA.predict(
    X_test.toarray()
)

pred_A_classes = pred_A.argmax(axis=1)

true_classes = y_test_onehot.argmax(axis=1)

In [ ]:
print(
    classification_report(
        true_classes,
        pred_A_classes
    )
)